"use strict";
const $ = id => document.getElementById(id);
let D = JSON.parse($("payload").textContent);
const originalHTML = "<!doctype html>\n" + document.documentElement.outerHTML;
const norm = value => String(value || "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^\p{L}\p{N}]+/gu, " ").trim().replace(/\s+/g, " ");
const esc = value => String(value ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
const fmt = value => Number(value || 0).toLocaleString("pt-BR");
const pct = (n, d) => d ? 100 * n / d : null;
const percent = value => value === null ? "sem denominador" : value.toLocaleString("pt-BR", {maximumFractionDigits: 1}) + "%";
const unique = a => [...new Set(a)].sort((a, b) => String(a).localeCompare(String(b), "pt-BR"));
const count = (rows, field) => {const c = Object.create(null); for (const r of rows) for (const k of (typeof field === "function" ? field(r) : [r[field]])) c[k] = (c[k] || 0) + 1; return c;};
const rank = c => Object.entries(c).sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0], "pt-BR"));
const palette = ["#2563eb", "#d97706", "#0d9488", "#7c3aed", "#dc2626", "#0891b2", "#c026d3", "#65a30d", "#e11d48", "#4f46e5", "#a16207", "#475569", "#059669", "#9333ea", "#0e7490", "#b91c1c", "#a21caf", "#4d7c0f", "#b45309", "#1e40af", "#be185d", "#334155"];
const fixedColors = {
 "Mercosul":"#2563eb", "UE":"#d97706", "União Europeia":"#d97706", "América Latina":"#0d9488", "Global":"#7c3aed", "Não informada":"#64748b", "Outra":"#64748b",
 "Brasil":"#2563eb", "Argentina":"#0891b2", "Uruguai":"#4f46e5", "Paraguai":"#c026d3", "Regional":"#0d9488",
 "Proteção de dados":"#059669", "GDPR/LGPD e proteção de dados":"#059669", "Privacidade":"#059669", "IA / algoritmos":"#0891b2", "Inteligência artificial":"#0891b2", "Algoritmos":"#0891b2", "AI Act":"#0891b2",
 "Plataformas / moderação":"#9333ea", "Plataformas":"#9333ea", "Moderação":"#9333ea", "DSA":"#9333ea", "Internet / governança":"#b45309", "Internet":"#b45309", "Governança digital":"#b45309",
 "Proteção infantil":"#e11d48", "Governança digital no Mercosul":"#2563eb", "UE–Mercosul":"#7c3aed", "Mercosul / UE / cooperação":"#2563eb", "Sul Global":"#c026d3", "Sul Global / soberania":"#c026d3", "Soberania digital":"#c026d3",
 "Notícia/comunicado":"#2563eb", "Publicação institucional":"#0d9488", "Fonte curada":"#d97706", "Evento da Biblioteca":"#7c3aed", "Registro sem data":"#94a3b8", "Página institucional":"#475569", "Referência institucional":"#a16207",
 "Dia exato":"#2563eb", "Somente mês":"#d97706", "Somente ano":"#7c3aed", "Sem data":"#94a3b8",
 "IA e proteção de dados":"#7c3aed", "Somente IA / algoritmos":"#0891b2", "Somente proteção de dados":"#059669", "Sem os dois marcadores":"#94a3b8"
};
function color(label, kind = "") {
 const aliases = {"mercosur":"Mercosul", "uniao europeia":"União Europeia", "ia e protecao de dados amplo":"IA / algoritmos"};
 label = aliases[norm(label)] || label;
 if (fixedColors[label] && kind !== "source") return fixedColors[label];
 D.color_registry = D.color_registry || {};
 const key = kind + ":" + label;
 if (!D.color_registry[key]) {let h = 2166136261; for (const c of key) h = Math.imul(h ^ c.charCodeAt(0), 16777619); let selected=palette[(h >>> 0) % palette.length];if(kind==="source"){const used=new Set(Object.entries(D.color_registry).filter(([k])=>k.startsWith("source:")).map(([,v])=>v));for(let i=0;i<palette.length&&used.has(selected);i++)selected=palette[((h>>>0)+i+1)%palette.length];if(used.has(selected))selected="hsl("+((h>>>0)%360)+",65%,42%)";}D.color_registry[key]=selected;}
 return D.color_registry[key];
}
const families = {
 "Proteção de dados":["GDPR","LGPD","Proteção de dados","Privacidade","Transferências de dados","Adequação","ANPD","EDPB"],
 "IA / algoritmos":["Inteligência artificial","Algoritmos","AI Act"],
 "Plataformas / moderação":["Plataformas","Moderação","DSA"], "Proteção infantil":["Proteção infantil"],
 "Internet / governança":["Internet","Governança digital"], "Mercosul / UE / cooperação":["Mercosul","União Europeia","Cooperação digital","Comércio digital"],
 "Sul Global / soberania":["Sul Global","Soberania digital"]
};
const aiTerms = ["Inteligência artificial","Algoritmos","AI Act"];
const dataTerms = ["GDPR","LGPD","Proteção de dados","Privacidade","Transferências de dados","Adequação"];
const hasAny = (row, terms) => terms.some(k => row.keywords.includes(k));
const isPublication = row => ["Notícia/comunicado", "Publicação institucional"].includes(row.record_type) && row.date_precision === "day";
const filterDefs = {region:"Âmbitos",country:"Países",source:"Fontes",record_type:"Tipos de registro",topics:"Eixos temáticos",keywords:"Palavras-chave"};
let filters = {}, series = {}, hiddenSeries = {}, page = 0, renderGeneration = 0, lastAnalytics = null;
let initialState = {}; try {initialState = JSON.parse($("saved-state").textContent || "{}");} catch (_) {}

function safeURL(value) {
 try {const u = new URL(String(value)); if (!["http:", "https:"].includes(u.protocol) || u.username || u.password) return "";
  u.hash = ""; for (const k of [...u.searchParams.keys()]) if (/^utm_/i.test(k) || ["fbclid", "gclid"].includes(k)) u.searchParams.delete(k);
  u.pathname = u.pathname.replace(/\/$/, "") || "/"; u.searchParams.sort(); return u.href.replace(/\/$/, "");
 } catch (_) {return "";}
}
function parseDate(value) {
 const raw = String(value || "").trim(); let m;
 function day(y, mo, d) {const date = new Date(Date.UTC(+y, +mo - 1, +d)); return date.getUTCFullYear() === +y && date.getUTCMonth() === +mo - 1 && date.getUTCDate() === +d ? [date.toISOString().slice(0, 10), "day"] : ["", "unknown"];}
 if ((m = raw.match(/^(\d{4})-(\d{2})-(\d{2})(?:T|\s|$)/))) return day(m[1], m[2], m[3]);
 if ((m = raw.match(/\b(\d{1,2})[./](\d{1,2})[./](\d{4})\b/))) return day(m[3], m[2], m[1]);
 const months = {janeiro:1,enero:1,january:1,fevereiro:2,febrero:2,february:2,marco:3,marzo:3,march:3,abril:4,april:4,maio:5,mayo:5,may:5,junho:6,junio:6,june:6,julho:7,julio:7,july:7,agosto:8,august:8,setembro:9,septiembre:9,setiembre:9,september:9,outubro:10,octubre:10,october:10,novembro:11,noviembre:11,november:11,dezembro:12,diciembre:12,december:12};
 if ((m = norm(raw).match(/\b(\d{1,2}) (?:de )?([a-z]+) (?:de )?(\d{4})\b/)) && months[m[2]]) return day(m[3], months[m[2]], m[1]);
 if ((m = norm(raw).match(/\b([a-z]+) (\d{1,2}) (\d{4})\b/)) && months[m[1]]) return day(m[3], months[m[1]], m[2]);
 if ((m = raw.match(/^(\d{4})-(\d{2})$/)) && +m[2] >= 1 && +m[2] <= 12) return [raw, "month"];
 if (/^\d{4}$/.test(raw)) return [raw, "year"];
 return ["", "unknown"];
}
function parseCSV(text) {
 text = String(text).replace(/^\uFEFF/, "");
 let first = "", quoted = false;
 for (let i = 0; i < text.length; i++) {const c = text[i]; if (c === '"') {if (quoted && text[i+1] === '"') {first += '""'; i++; continue;} quoted = !quoted;} if (!quoted && (c === "\n" || c === "\r")) break; first += c;}
 const candidates = [",", ";", "\t"].map(d => {let n=0,q=false;for(let i=0;i<first.length;i++){if(first[i]==='"'){if(q&&first[i+1]==='"'){i++;continue;}q=!q;}else if(!q&&first[i]===d)n++;}return[d,n];}).sort((a,b)=>b[1]-a[1]);
 const delimiter = candidates[0][0], rows = []; let row=[], value=""; quoted=false;
 for (let i=0;i<text.length;i++) {const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){value+='"';i++;}else if(quoted||value==='')quoted=!quoted;else value+=c;}else if(!quoted&&c===delimiter){row.push(value);value="";}else if(!quoted&&(c==='\n'||c==='\r')){if(c==='\r'&&text[i+1]==='\n')i++;row.push(value);if(row.some(x=>x.trim()))rows.push(row);row=[];value="";}else value+=c;}
 if(quoted)throw Error("CSV com aspas não fechadas.");if(value||row.length){row.push(value);if(row.some(x=>x.trim()))rows.push(row);}
 if(rows.length<2)throw Error("O CSV precisa de cabeçalho e ao menos um registro.");
 const headers=rows.shift().map(x=>x.trim());if(new Set(headers.map(norm)).size!==headers.length)throw Error("CSV com cabeçalhos duplicados.");
 return rows.map((r,i)=>{if(r.length!==headers.length)throw Error("Número de colunas diferente do cabeçalho na linha "+(i+2));return Object.fromEntries(headers.map((h,j)=>[h,r[j]]));});
}
function normalizeRecord(raw, filename="importado") {
 const fields = Object.fromEntries(Object.entries(raw).map(([k,v])=>[norm(k).replace(/ /g,"_"),v]));
 const get=(...names)=>{for(const n of names)if(fields[n]!==undefined&&fields[n]!=="")return fields[n];return "";};
 const title=String(get("title","titulo","manchete","news_title")).replace(/\s+/g," ").trim();
 const url=safeURL(get("url","link","permalink","href"));if(!title||!url)return null;
 const suppliedDate=get("published_date","data","date","fecha","data_publicacao","data_de_publicacao","published","raw_date");
 const [published_date,date_precision]=parseDate(suppliedDate);
 const host=new URL(url).hostname.replace(/^www\./,"");
 const metas=D.source_meta||{};
 let sid=String(get("source_id","fonte","source","origem","instituicao"));
 if(!sid) {sid=Object.keys(metas).find(k=>(metas[k].hosts||[]).some(h=>host===h||host.endsWith("."+h)))||("Fonte: "+host);}
 if(!metas[sid]) {const match=Object.keys(metas).find(k=>norm(metas[k].source)===norm(sid));if(match)sid=match;}
 const meta=metas[sid]||{};
 const manually_selected=raw.manually_selected===true||String(raw.manually_selected).toLowerCase()==="true"||get("corpus")==="catalogo";
 const type=String(get("record_type","tipo_registro")||(manually_selected?"Fonte curada":published_date?((sid==="dataprivacy")?"Publicação institucional":"Notícia/comunicado"):"Registro sem data"));
 return {...raw,title,url,canonical_url:url,source_id:sid,source:String(get("source")||meta.source||sid),country:String(get("country","pais")||meta.country||"Não informada"),region:String(get("region","regiao","ambito")||meta.region||"Não informada"),
  record_type:type,published_date,date_precision,published_raw:String(suppliedDate),summary:String(get("summary","resumo","descricao","abstract")||""),
  manually_selected,corpora:Array.isArray(raw.corpora)?raw.corpora:manually_selected?["catalogo"]:["scrapers"],corpus:manually_selected?"catalogo":"scrapers",input_snapshots:Array.isArray(raw.input_snapshots)?raw.input_snapshots:[filename],collected_at:get("collected_at","last_seen")||"",category:get("category","categories","categoria")||""};
}
function classify(rows) {
 const mode=$("analysis-text").value, cfg=D.config, relevance=new Set(cfg.relevance_keywords||[]);
 for(const r of rows) {const text=norm(r.title+(mode==="title_summary"?" "+(r.summary||""):""));
  const hits={};for(const [label,aliases]of Object.entries(cfg.keywords)){const matched=aliases.map(norm).filter(a=>(" "+text+" ").includes(" "+a+" "));if(matched.length)hits[label]=matched;}
  r.keywords=Object.keys(hits);r.candidate=r.keywords.some(k=>relevance.has(k));r.analysis_text=mode==="title_summary"?r.title+" "+(r.summary||""):r.title;
  r.topics=Object.entries(cfg.axes).filter(([,rule])=>(!rule.any_keywords||rule.any_keywords.some(k=>r.keywords.includes(k)))&&(!rule.all_groups||rule.all_groups.every(g=>g.some(k=>r.keywords.includes(k))))).map(([label])=>label);
  r.match_evidence=Object.entries(hits).map(([k,a])=>k+": "+a.join(", ")).join("; ");
 }
}
function values(field) {if(field==="topics")return Object.keys(D.config.axes);if(field==="keywords")return Object.keys(D.config.keywords);return unique(D.documents.map(r=>r[field]||"Não informada"));}
function defaultFilter(field, options) {return field==="record_type"?options.filter(k=>["Notícia/comunicado","Publicação institucional","Fonte curada"].includes(k)):field==="topics"||field==="keywords"?[]:options;}
function buildFilters(preserve=true) {
 const container=$("filter-groups");container.replaceChildren();
 for(const [field,title]of Object.entries(filterDefs)) {const options=values(field), previous=filters[field];filters[field]=previous&&preserve?previous.filter(k=>options.includes(k)):defaultFilter(field,options);
  const details=document.createElement("details"),summary=document.createElement("summary"),tag=document.createElement("span");summary.textContent=title;tag.className="count-tag";tag.id="filter-count-"+field;summary.append(tag);details.append(summary);
  const tools=document.createElement("div");tools.className="choice-tools";
  for(const [label,selection]of [["Todas",()=>options.slice()],[(field==="topics"||field==="keywords")?"Sem restrição":"Nenhuma",()=>[]]]){const button=document.createElement("button");button.textContent=label;button.onclick=()=>{filters[field]=selection();buildFilters();render();};tools.append(button);}details.append(tools);
  const search=document.createElement("input");search.type="search";search.placeholder="Procurar opção…";search.className="filter-search";search.setAttribute("aria-label","Procurar em "+title);details.append(search);
  const choices=document.createElement("div");choices.className="choices";
  for(const option of options){const label=document.createElement("label"),input=document.createElement("input"),dot=document.createElement("span");input.type="checkbox";input.checked=filters[field].includes(option);input.dataset.field=field;input.value=option;input.onchange=()=>{filters[field]=input.checked?unique([...filters[field],option]):filters[field].filter(x=>x!==option);updateFilterLabels();render();};dot.className="dot";dot.style.background=color(option,field);label.append(input,dot,document.createTextNode(option));label.dataset.search=norm(option);choices.append(label);}search.oninput=()=>{for(const l of choices.children)l.hidden=!l.dataset.search.includes(norm(search.value));};details.append(choices);container.append(details);
 }
 updateFilterLabels();
}
function updateFilterLabels(){for(const field of Object.keys(filterDefs)){const n=filters[field].length,total=values(field).length;$("filter-count-"+field).textContent=(field==="topics"||field==="keywords")&&!n?"sem restrição":n+" / "+total;}}
function selected(){
 const start=$("start").value,end=$("end").value,query=norm($("query").value);if(start&&end&&start>end)return [];
 return D.documents.filter(r=>{
  for(const field of ["region","country","source","record_type"])if(!filters[field].includes(r[field]))return false;
  for(const field of ["topics","keywords"])if(filters[field].length&&!filters[field].some(k=>r[field].includes(k)))return false;
  if($("candidates-only").checked&&!r.candidate&&!r.manually_selected)return false;
  if(query&&!norm(r.title+" "+(r.summary||"")+" "+r.source).includes(query))return false;
  if(r.date_precision!=="day"&&!$("include-undated").checked)return false;
  if(r.date_precision==="day"&&((start&&r.published_date<start)||(end&&r.published_date>end)))return false;
  if(["month","year"].includes(r.date_precision)&&((start&&r.published_date<start.slice(0,r.published_date.length))||(end&&r.published_date>end.slice(0,r.published_date.length))))return false;
  return true;
 }).sort((a,b)=>b.published_date.localeCompare(a.published_date)||a.title.localeCompare(b.title));
}
const plotConfig={responsive:true,displaylogo:false,modeBarButtonsToRemove:["select2d","lasso2d","toImage"]};
function layout(height=450){return {height,template:"plotly_white",paper_bgcolor:"#fff",plot_bgcolor:"#fff",font:{family:"Arial, sans-serif",size:12,color:"#172b43"},margin:{l:210,r:85,t:30,b:75},xaxis:{automargin:true,gridcolor:"#e8eef5",zeroline:false},yaxis:{automargin:true,gridcolor:"#e8eef5",zeroline:false},legend:{orientation:"h",y:-.32,x:0},uirevision:"fapesp-colors-v3"};}
function wrap(label,width=28){const words=String(label).split(/\s+/),lines=[];let line="";for(const word of words){if(line&&line.length+word.length>width){lines.push(line);line=word;}else line+=(line?" ":"")+word;}if(line)lines.push(line);return lines.slice(0,3).map(esc).join("<br>");}
function plot(id,traces,l){const el=$(id),heading=el.closest("article,section")?.querySelector("h3,h2"),A=lastAnalytics;const diagnostic=["chart-coverage","chart-date-quality"].includes(id),caption=diagnostic?"Diagnóstico: "+($("audit-scope").value==="all"?"base completa":"seleção atual")+" · N = "+fmt(A?.audit.length):"Publicações: N = "+fmt(A?.news.length)+" · "+($("start").value||"histórico")+" a "+($("end").value||"fim da base")+" · "+($("analysis-text").value==="title"?"títulos":"títulos + resumos");l.title={text:wrap(heading?.textContent||"Análise FAPESP",65)+"<br><sup>"+esc(caption)+(id==="chart-cohort"?" · catálogo: N = "+fmt(A?.catalog.length):"")+"</sup>",font:{size:16},x:.02,xanchor:"left"};l.margin.t=105;if(!traces.length){l.annotations=[{text:"Sem registros elegíveis neste recorte",xref:"paper",yref:"paper",x:.5,y:.5,showarrow:false}];}return Plotly.react(id,traces,l,plotConfig);}
function bar(id,entries,denominator,kind="",limit=20,axis="Publicações"){
 const r=entries.slice(0,limit).reverse(),l=layout(Math.max(400,r.length*44+110));l.margin.l=230;l.xaxis={...l.xaxis,title:{text:axis},range:[0,Math.max(1,...r.map(x=>x[1]))*1.3],tickformat:",d",nticks:7};l.yaxis={...l.yaxis,tickmode:"array",tickvals:r.map((_,i)=>i),ticktext:r.map(x=>wrap(x[0])),range:[-.7,Math.max(.7,r.length-.3)]};
 return plot(id,r.length?[{type:"bar",orientation:"h",y:r.map((_,i)=>i),x:r.map(x=>x[1]),marker:{color:r.map(x=>color(x[0],kind))},text:r.map(x=>fmt(x[1])+" · "+percent(pct(x[1],denominator))),textposition:"outside",cliponaxis:false,customdata:r.map(x=>[esc(x[0]),denominator,x[0]]),hovertemplate:"%{customdata[0]}<br>%{x} / %{customdata[1]} publicações<extra></extra>"}]:[],l);
}
function monthLabels(rows){if(!rows.length)return [];const dates=rows.map(r=>r.published_date.slice(0,7)).sort(),out=[];let d=new Date(dates[0]+"-01T12:00:00Z");const last=dates.at(-1);for(let i=0;i<1200&&d.toISOString().slice(0,7)<=last;i++){out.push(d.toISOString().slice(0,7));d.setUTCMonth(d.getUTCMonth()+1);}return out;}
function analytics(rows){
 const news=rows.filter(isPublication),catalog=rows.filter(r=>r.manually_selected),sourceCounts=rank(count(news,"source")),keywordCounts=rank(count(news,r=>r.keywords)),axes=Object.keys(D.config.axes);
 const intersection=["IA e proteção de dados","Somente IA / algoritmos","Somente proteção de dados","Sem os dois marcadores"].map(label=>({label,n:0}));for(const r of news){const a=hasAny(r,aiTerms),b=hasAny(r,dataTerms);intersection[a?(b?0:1):(b?2:3)].n++;}
 const pairs=[];for(let i=0;i<keywordCounts.length;i++)for(let j=i+1;j<keywordCounts.length;j++){const a=keywordCounts[i][0],b=keywordCounts[j][0],n=news.filter(r=>r.keywords.includes(a)&&r.keywords.includes(b)).length,union=keywordCounts[i][1]+keywordCounts[j][1]-n;if(n>=+$("pair-min").value)pairs.push({a,b,n,union,jaccard:n/union});}pairs.sort((a,b)=>b.jaccard-a.jaccard||b.n-a.n);
 const profile=sourceCounts.map(([source,n])=>({source,n,values:Object.entries(families).map(([label,terms])=>({label,n:news.filter(r=>r.source===source&&hasAny(r,terms)).length}))}));
 const audit=$("audit-scope").value==="all"?D.documents:rows,countries=rank(count(audit,"country")).map(x=>x[0]),types=unique(audit.map(r=>r.record_type));
 const quality=rank(count(audit,"source")).map(([source,n])=>({source,n,day:audit.filter(r=>r.source===source&&r.date_precision==="day").length,month:audit.filter(r=>r.source===source&&r.date_precision==="month").length,year:audit.filter(r=>r.source===source&&r.date_precision==="year").length,unknown:audit.filter(r=>r.source===source&&r.date_precision==="unknown").length}));
 let cumulative=0;const concentration=sourceCounts.map(([source,n])=>{cumulative+=n;return {source,n,share:pct(n,news.length),cumulative:pct(cumulative,news.length)};});
 const stop=new Set(norm(D.config.stopwords).split(" ")),wordCounts={};for(const r of news)for(const word of new Set(norm(r.analysis_text).split(" ").filter(w=>w.length>=4&&!/^\d+$/.test(w)&&!stop.has(w))))wordCounts[word]=(wordCounts[word]||0)+1;
 return {rows,news,catalog,sourceCounts,keywordCounts,axes,intersection,pairs,profile,audit,countries,types,quality,concentration,wordCounts};
}
function groupRows(rows,field,label){return rows.filter(r=>Array.isArray(r[field])?r[field].includes(label):r[field]===label);}
function buildSeries(){const field=$("compare-group").value,options=values(field);if(!series[field])series[field]=options.slice();else series[field]=series[field].filter(x=>options.includes(x));const target=$("comparison-series");target.replaceChildren();for(const name of options){const label=document.createElement("label"),check=document.createElement("input"),dot=document.createElement("span");check.type="checkbox";check.checked=series[field].includes(name);check.value=name;check.dataset.series=field;check.onchange=()=>{series[field]=check.checked?unique([...series[field],name]):series[field].filter(x=>x!==name);delete hiddenSeries[field+":"+name];render();};dot.className="dot";dot.style.background=color(name,field);label.append(check,dot,document.createTextNode(name));target.append(label);}}
async function comparison(A){
 const field=$("compare-group").value,view=$("compare-view").value,metric=$("compare-metric").value,traces=[],l=layout(510);l.margin={l:70,r:30,t:25,b:140};l.yaxis={...l.yaxis,title:{text:metric==="percent"?"% dentro de cada série":"Publicações"},rangemode:"tozero"};
 const months=monthLabels(A.news),names=series[field]||[];
 for(const name of names){const group=groupRows(A.news,field,name);if(!group.length)continue;const topics=Object.keys(families);let x,y,nums;
  if(view==="time"){x=months;nums=x.map(m=>group.filter(r=>r.published_date.startsWith(m)).length);}else if(view==="themes"){x=topics;nums=topics.map(t=>group.filter(r=>hasAny(r,families[t])).length);}else{x=["Total da série"];nums=[group.length];}
  y=nums.map(n=>metric==="percent"?pct(n,group.length):n);
  const key=field+":"+name;traces.push({type:view==="time"?"scatter":"bar",mode:"lines+markers",name:esc(name),x:x.map(esc),y,line:{color:color(name,field),width:2},marker:{color:color(name,field)},visible:hiddenSeries[key]?"legendonly":true,customdata:nums.map(n=>[n,group.length,esc(name)]),hovertemplate:"%{customdata[2]}<br>%{x}<br>%{customdata[0]} / %{customdata[1]} publicações<extra></extra>"});
 }
 l.barmode="group";l.xaxis.tickangle=view==="time"?0:-25;
 if(metric==="percent")l.yaxis.ticksuffix="%";
 $("comparison-note").textContent="Base: "+fmt(A.news.length)+" publicações com data exata. "+(metric==="percent"?"Cada série tem seu próprio denominador; consulte-o no cursor.":"Contagens do recorte.")+" Séries sem registros não são desenhadas.";
 await plot("chart-comparison",traces,l);
 const el=$("chart-comparison");if(el.removeAllListeners)el.removeAllListeners("plotly_restyle");if(el.on)el.on("plotly_restyle",()=>{for(const trace of el.data||[]){const name=String(trace.name).replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"');hiddenSeries[field+":"+name]=trace.visible==="legendonly";}});
}
async function draw(A){
 const jobs=[];jobs.push(bar("chart-sources",A.sourceCounts,A.news.length,"source",30));jobs.push(bar("chart-keywords",A.keywordCounts,A.news.length,"keywords",24));jobs.push(bar("chart-topics",A.axes.map(a=>[a,A.news.filter(r=>r.topics.includes(a)).length]),A.news.length,"topics",20));
 jobs.push(bar("chart-countries",rank(count(A.news,"country")),A.news.length,"country"));jobs.push(bar("chart-scopes",rank(count(A.news,"region")),A.news.length,"region"));jobs.push(bar("chart-words",rank(A.wordCounts),A.news.length,"words",20));
 const profile=A.profile.slice(0,30).reverse(),pl=layout(Math.max(460,profile.length*46+190));pl.margin={l:225,r:85,t:30,b:150};pl.xaxis.tickangle=-30;
 jobs.push(plot("chart-profile",profile.length?[{type:"heatmap",x:Object.keys(families).map(t=>wrap(t,18)),y:profile.map(p=>wrap(p.source)),z:profile.map(p=>p.values.map(v=>pct(v.n,p.n))),zmin:0,zmax:100,colorscale:[[0,"#f1f5f9"],[.5,"#93b4e8"],[1,"#1d4ed8"]],customdata:profile.map(p=>p.values.map(v=>[v.n,p.n,esc(p.source),esc(v.label)])),text:profile.map(p=>p.values.map(v=>Math.round(pct(v.n,p.n))+"%")),texttemplate:"%{text}",hovertemplate:"%{customdata[2]}<br>%{customdata[3]}<br>%{customdata[0]} / %{customdata[1]} · %{z:.1f}%<extra></extra>",colorbar:{title:{text:"%"}}}]:[],pl));
 const ml=layout(480),months=monthLabels(A.news),scopes=unique(A.news.map(r=>r.region));ml.margin={l:70,r:25,t:25,b:100};ml.yaxis.title={text:"Publicações"};
 jobs.push(plot("chart-months",scopes.map(region=>{const group=A.news.filter(r=>r.region===region);return {type:"scatter",mode:"lines+markers",name:esc(region),x:months,y:months.map(m=>group.filter(r=>r.published_date.startsWith(m)).length),line:{color:color(region),width:2.5},marker:{color:color(region)},hovertemplate:"%{x}<br>%{y} publicações<extra>"+esc(region)+"</extra>"};}),ml));
 const cl=layout(510);cl.xaxis={...cl.xaxis,title:{text:"% dentro de cada conjunto"},range:[0,110],ticksuffix:"%"};cl.margin.l=240;cl.barmode="group";
 jobs.push(plot("chart-cohort",(A.news.length||A.catalog.length)?[{type:"bar",orientation:"h",name:"Publicações datadas",y:A.axes.map(a=>wrap(a)),x:A.axes.map(a=>pct(A.news.filter(r=>r.topics.includes(a)).length,A.news.length)),marker:{color:A.axes.map(a=>color(a))},customdata:A.axes.map(a=>[A.news.filter(r=>r.topics.includes(a)).length,A.news.length]),hovertemplate:"%{y}<br>%{customdata[0]} / %{customdata[1]} · %{x:.1f}%<extra>Publicações</extra>"},{type:"bar",orientation:"h",name:"Catálogo curado",y:A.axes.map(a=>wrap(a)),x:A.axes.map(a=>pct(A.catalog.filter(r=>r.topics.includes(a)).length,A.catalog.length)),marker:{color:A.axes.map(a=>color(a)),opacity:.35,line:{width:1,color:A.axes.map(a=>color(a))}},customdata:A.axes.map(a=>[A.catalog.filter(r=>r.topics.includes(a)).length,A.catalog.length]),hovertemplate:"%{y}<br>%{customdata[0]} / %{customdata[1]} · %{x:.1f}%<extra>Catálogo</extra>"}]:[],cl));
 jobs.push(bar("chart-intersection",A.intersection.map(x=>[x.label,x.n]),A.news.length,"",4));
 const pairs=A.pairs.slice(0,12).reverse(),rl=layout(Math.max(430,pairs.length*48+110));rl.xaxis={...rl.xaxis,title:{text:"Jaccard · interseção / união"},range:[0,1]};rl.margin.l=290;
 jobs.push(plot("chart-ranked-pairs",pairs.length?[{type:"bar",orientation:"h",x:pairs.map(p=>p.jaccard),y:pairs.map(p=>wrap(p.a+" + "+p.b,35)),marker:{color:pairs.map(p=>color(p.a+" + "+p.b,"pair"))},customdata:pairs.map(p=>[p.n,p.union]),text:pairs.map(p=>p.n+" em comum"),textposition:"outside",cliponaxis:false,hovertemplate:"%{y}<br>%{customdata[0]} em comum / %{customdata[1]} na união<br>Jaccard: %{x:.3f}<extra></extra>"}]:[],rl));
 const labels=A.keywordCounts.slice(0,12).map(x=>x[0]),hm=layout(640);hm.margin={l:200,r:65,t:25,b:190};hm.xaxis.tickangle=-35;const z=labels.map(a=>labels.map(b=>A.news.filter(r=>r.keywords.includes(a)&&r.keywords.includes(b)).length));
 jobs.push(plot("chart-pairs",labels.length?[{type:"heatmap",x:labels.map(x=>wrap(x,18)),y:labels.map(x=>wrap(x,18)),z,colorscale:"Blues",text:z,texttemplate:"%{text}",hovertemplate:"%{y} + %{x}<br>%{z} publicações<extra></extra>",colorbar:{title:{text:"N"}}}]:[],hm));
 const gl=layout(470);gl.margin={l:65,r:30,t:25,b:180};gl.barmode="group";gl.xaxis.tickangle=-30;gl.yaxis={...gl.yaxis,title:{text:"% dentro do âmbito"},ticksuffix:"%",range:[0,110]};
 jobs.push(plot("chart-regions",scopes.map(region=>{const group=A.news.filter(r=>r.region===region);return {type:"bar",name:esc(region),x:Object.keys(families).map(t=>wrap(t,20)),y:Object.values(families).map(terms=>pct(group.filter(r=>hasAny(r,terms)).length,group.length)),marker:{color:color(region)},customdata:Object.values(families).map(terms=>[group.filter(r=>hasAny(r,terms)).length,group.length]),hovertemplate:"%{x}<br>%{customdata[0]} / %{customdata[1]} · %{y:.1f}%<extra>"+esc(region)+"</extra>"};}),gl));
 const cv=layout(500);cv.margin={l:160,r:40,t:25,b:145};cv.barmode="stack";cv.xaxis.title={text:"Registros"};$("coverage-note").textContent="Escopo: "+($("audit-scope").value==="all"?"base completa, sem filtros":"seleção atual")+" · "+fmt(A.audit.length)+" registros. Eventos, páginas institucionais e publicações têm categorias próprias.";
 jobs.push(plot("chart-coverage",A.audit.length?A.types.map(type=>({type:"bar",orientation:"h",name:esc(type),y:A.countries.map(esc),x:A.countries.map(c=>A.audit.filter(r=>r.country===c&&r.record_type===type).length),marker:{color:color(type)},hovertemplate:"%{y}<br>%{x} registros<extra>"+esc(type)+"</extra>"})):[],cv));
 const q=A.quality.slice(0,35).reverse(),ql=layout(Math.max(450,q.length*38+180));ql.margin={l:235,r:50,t:25,b:130};ql.barmode="stack";ql.xaxis={...ql.xaxis,title:{text:"% dos registros da fonte"},ticksuffix:"%",range:[0,100]};
 jobs.push(plot("chart-date-quality",q.length?[["day","Dia exato"],["month","Somente mês"],["year","Somente ano"],["unknown","Sem data"]].map(([key,label])=>({type:"bar",orientation:"h",name:label,y:q.map(x=>wrap(x.source)),x:q.map(x=>pct(x[key],x.n)),marker:{color:color(label)},customdata:q.map(x=>[x[key],x.n]),hovertemplate:"%{y}<br>%{customdata[0]} / %{customdata[1]} · %{x:.1f}%<extra>"+label+"</extra>"})):[],ql));
 const cn=A.concentration,con=layout(560);con.margin={l:65,r:70,t:30,b:190};con.xaxis={...con.xaxis,tickangle:-40};con.yaxis={...con.yaxis,title:{text:"Participação da fonte (%)"},ticksuffix:"%",rangemode:"tozero"};con.yaxis2={overlaying:"y",side:"right",range:[0,105],title:{text:"Acumulada (%)"},ticksuffix:"%",showgrid:false};
 jobs.push(plot("chart-concentration",cn.length?[{type:"bar",name:"Participação",x:cn.map(x=>wrap(x.source,21)),y:cn.map(x=>x.share),marker:{color:cn.map(x=>color(x.source,"source"))},customdata:cn.map(x=>[x.n,A.news.length]),hovertemplate:"%{x}<br>%{customdata[0]} / %{customdata[1]} · %{y:.1f}%<extra></extra>"},{type:"scatter",mode:"lines+markers",name:"Acumulada",x:cn.map(x=>wrap(x.source,21)),y:cn.map(x=>x.cumulative),yaxis:"y2",line:{color:"#334155"},hovertemplate:"%{x}<br>Acumulada: %{y:.1f}%<extra></extra>"}]:[],con));
 jobs.push(comparison(A));await Promise.all(jobs);
}
function table(rows){const body=$("documents").querySelector("tbody");body.replaceChildren();const pages=Math.max(1,Math.ceil(rows.length/40));page=Math.min(Math.max(0,page),pages-1);for(const r of rows.slice(page*40,page*40+40)){const tr=document.createElement("tr");for(let i=0;i<5;i++){const td=document.createElement("td");if(i===0){const a=document.createElement("a");a.href=r.url;a.target="_blank";a.rel="noopener noreferrer";a.textContent=r.title;td.append(a);if(r.manually_selected){const p=document.createElement("div");p.className="pill";p.textContent="Catálogo curado";td.append(p);}}else if(i===1){td.textContent=r.source;const note=document.createElement("div");note.className="meta-line";note.textContent=r.country+" · "+r.region;td.append(note);}else if(i===2){td.textContent=r.published_date||"Não informada";const note=document.createElement("div");note.className="meta-line";note.textContent=r.record_type+" · precisão: "+({day:"dia",month:"mês",year:"ano",unknown:"ausente"}[r.date_precision]);td.append(note);}else if(i===3){td.textContent=r.keywords.join("; ")+"\n"+r.topics.join("; ");td.style.whiteSpace="pre-line";}else{td.textContent=(r.catalog_summary||r.summary||"").slice(0,850);const note=document.createElement("div");note.className="meta-line";note.textContent=(r.input_snapshots||[]).join(" · ")+(r.collected_at?" · Coleta: "+r.collected_at:"");td.append(note);}tr.append(td);}body.append(tr);}if(!rows.length){const tr=document.createElement("tr"),td=document.createElement("td");td.colSpan=5;td.textContent="Nenhum registro neste recorte. Amplie os filtros.";tr.append(td);body.append(tr);}$("page-label").textContent="Página "+(page+1)+" de "+pages;$("prev").disabled=page===0;$("next").disabled=page>=pages-1;$("table-note").textContent=fmt(rows.length)+" registros; CSV exporta toda a seleção, com URLs e proveniência.";}
function health(){const reports=D.diagnostics?.sources||[],body=$("source-health").querySelector("tbody");body.replaceChildren();const labels={ok:"Coletado com datas",partial:"Coleta parcial / incompleta",failed:"Falha de acesso / coleta",empty:"Sem registros extraídos",reference_only:"Página institucional",historical:"Somente histórico",duplicate_source:"Coleta duplicada"};for(const r of reports){const tr=document.createElement("tr");for(const [i,value]of [r.source+" · "+(r.region||""),labels[r.status]||r.status,fmt(r.records||r.seen),fmt(r.dated||0),(r.method||"")+" · "+(r.coverage||r.coverage_note||""),(r.errors||[]).map(e=>typeof e==="string"?e:e.error).concat(r.warnings||[]).join("; ")].entries()){const td=document.createElement("td");td.textContent=value;if(i===1)td.className="source-status "+r.status;tr.append(td);}body.append(tr);}$("scraping-summary").textContent="Rodada: "+(D.diagnostics?.generated_at||"não informada")+" · "+reports.length+" fontes verificadas. Importar arquivos altera a base; os diagnósticos mudam quando um novo diagnóstico JSON é importado ou buscado no GitHub.";}
function metadata(){const at=D.metadata.generated_at||"não informada";$("reference").textContent=fmt(D.documents.length)+" URLs únicas na base · dados incorporados em "+at+" · escolha o período de publicação nos filtros";$("footer").textContent="Painel FAPESP · versão 3 · gráficos e dados incorporados. PNG e SVG podem ser baixados em cada gráfico; mantenha o período, denominador e método na legenda do relatório.";const legend=$("color-legend");legend.replaceChildren();for(const name of ["Mercosul","UE","América Latina","Global"]){const span=document.createElement("span"),dot=document.createElement("span");dot.className="dot";dot.style.background=color(name);span.append(dot,document.createTextNode(name));legend.append(span);}const dict=$("dictionary");dict.replaceChildren();for(const [label,aliases]of Object.entries(D.config.keywords)){const p=document.createElement("p"),dot=document.createElement("span");dot.className="dot";dot.style.background=color(label);p.append(dot,document.createTextNode(label+": "+aliases.join("; ")));dict.append(p);}health();}
async function render(){const generation=++renderGeneration;$("busy").textContent="Calculando análises…";const rows=selected();page=0;const A=analytics(rows);lastAnalytics=A;window.fapespAnalytics=A;window.curadoriaView=rows;$("n-records").textContent=fmt(rows.length);$("n-news").textContent=fmt(A.news.length);$("n-sources").textContent=fmt(unique(rows.map(r=>r.source)).length);$("n-matches").textContent=fmt(rows.filter(r=>r.candidate).length);$("n-undated").textContent=fmt(rows.filter(r=>r.date_precision!=="day").length);$("analytical-summary").textContent=fmt(A.news.length)+" publicações com data exata e "+fmt(A.catalog.length)+" itens do catálogo no recorte. Texto analisado: "+($("analysis-text").value==="title"?"títulos":"títulos e resumos disponíveis")+".";$("active-filters").textContent="Publicação: "+($("start").value||"início do histórico")+" a "+($("end").value||"fim do histórico")+" · "+filters.region.join(", ")+" · "+filters.source.length+" fontes selecionadas.";table(rows);try{await draw(A);if(generation===renderGeneration){$("busy").textContent=$("start").value&&$("end").value&&$("start").value>$("end").value?"Período inválido: a data inicial deve vir antes da final.":"Atualizado";bindChartClicks();}}catch(e){$("busy").textContent="Erro ao desenhar: "+e.message;console.error(e);}}
function bindChartClicks(){for(const [id,field]of [["chart-sources","source"],["chart-keywords","keywords"],["chart-topics","topics"],["chart-countries","country"],["chart-scopes","region"]]){const el=$(id);if(el.removeAllListeners)el.removeAllListeners("plotly_click");if(el.on)el.on("plotly_click",e=>{const meta=e.points?.[0]?.customdata;if(!meta)return;filters[field]=[meta[2]];buildFilters();render();});}}
function message(text,error=false){$("update-message").textContent=text;$("update-message").classList.toggle("error",error);}
function mergeRecords(incoming,mode="merge"){
 if(!incoming.length)throw Error("Nenhum registro válido com título e URL. A base foi preservada.");
 let base=D.documents;if(mode==="replace")base=base.filter(r=>r.manually_selected);if(mode==="source"){const ids=new Set(incoming.map(r=>r.source_id));base=base.filter(r=>!ids.has(r.source_id)||r.manually_selected);}
 const merged=new Map(base.map(r=>[safeURL(r.url),r]));let added=0,updated=0;
 for(const row of incoming){const old=merged.get(row.url);if(old){const result={...old,...row,manually_selected:!!(old.manually_selected||row.manually_selected),corpora:unique([...(old.corpora||[]),...(row.corpora||[])]),input_snapshots:unique([...(old.input_snapshots||[]),...(row.input_snapshots||[])])};for(const k of ["catalog_title","catalog_summary","catalog_source"])if(old[k])result[k]=old[k];if(old.date_precision==="day"&&row.date_precision!=="day")for(const k of ["published_date","date_precision","published_raw","record_type"])result[k]=old[k];if(!row.summary&&old.summary)result.summary=old.summary;merged.set(row.url,result);updated++;}else{merged.set(row.url,row);added++;}}
 const previousOptions=Object.fromEntries(Object.keys(filterDefs).map(k=>[k,values(k)])),unrestricted={};for(const k of ["region","country","source"])unrestricted[k]=filters[k].length===previousOptions[k].length;
 D.documents=[...merged.values()];const oldReference=D.metadata.as_of;D.metadata.generated_at=new Date().toISOString();D.metadata.as_of=D.metadata.generated_at.slice(0,10);if($("end").value===oldReference)$("end").value=D.metadata.as_of;D.metadata.last_import_at=D.metadata.generated_at;classify(D.documents);
 for(const k of ["region","country","source"])if(unrestricted[k])filters[k]=values(k);const oldTypes=filters.record_type;for(const type of ["Notícia/comunicado","Publicação institucional"])if(values("record_type").includes(type)&&!previousOptions.record_type.includes(type))oldTypes.push(type);
 buildFilters();for(const field of Object.keys(series))series[field]=unique([...series[field],...values(field).filter(v=>!previousOptions[field]?.includes(v))]);buildSeries();metadata();render();return {added,updated,total:D.documents.length};
}
function decodeJSON(object){if(Array.isArray(object))return {rows:object};if(Array.isArray(object.documents))return {rows:object.documents,diagnostics:object.diagnostics};if(Array.isArray(object.records))return {rows:object.records,diagnostics:object.diagnostics};if(Array.isArray(object.rows))return {rows:object.rows};if(Array.isArray(object.sources)&&object.generated_at)return {rows:[],diagnostics:object};throw Error("JSON deve conter lista de registros, documents/records/rows ou diagnóstico de fontes.");}
async function importFiles(files){const rows=[];let diagnostic=null,invalid=0;for(const file of files){const content=await file.text();const data=/\.json$/i.test(file.name)?decodeJSON(JSON.parse(content)):{rows:parseCSV(content)};if(data.diagnostics)diagnostic=data.diagnostics;for(const raw of data.rows){const r=normalizeRecord(raw,file.name);if(r)rows.push(r);else invalid++;}}
 if(!rows.length&&!diagnostic)throw Error("Não há registros nem diagnóstico válidos; a base foi preservada.");let stats={added:0,updated:0,total:D.documents.length};if(rows.length)stats=mergeRecords(rows,$("import-mode").value);if(diagnostic){D.diagnostics=diagnostic;health();}message(fmt(stats.added)+" novos; "+fmt(stats.updated)+" URLs atualizadas; "+fmt(stats.total)+" na base."+(invalid?" "+fmt(invalid)+" linhas sem título/URL foram ignoradas.":"")+" Clique em Salvar HTML atualizado para guardar esta versão.");return stats;
}
async function syncGithub(){const button=$("sync-github");button.disabled=true;message("Buscando a base pública e o diagnóstico de scraping…");try{const base="https://raw.githubusercontent.com/anamacao/FAPESP-PIBIC-scrapping/main/data/unified/";const fetchText=async url=>{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),30000);try{const r=await fetch(url,{cache:"no-store",signal:controller.signal});if(!r.ok)throw Error("GitHub retornou HTTP "+r.status);return await r.text();}finally{clearTimeout(timer);}};const results=await Promise.all([fetchText(base+"public_records.csv"),fetchText(base+"diagnostico.json")]);const rows=parseCSV(results[0]).map(r=>normalizeRecord(r,"Coleta pública GitHub")).filter(Boolean),diagnostic=JSON.parse(results[1]);if(!Array.isArray(diagnostic.sources))throw Error("Diagnóstico inválido; a base foi preservada.");const stats=mergeRecords(rows,"merge");D.diagnostics=diagnostic;health();message(fmt(stats.added)+" novos; "+fmt(stats.updated)+" atualizados. Rodada: "+diagnostic.generated_at+". Clique em Salvar HTML atualizado.");}catch(e){message("Não foi possível atualizar: "+e.message+". A base incorporada continua disponível. Você pode importar os arquivos do Colab.",true);}finally{button.disabled=false;}}
function jsonSafe(value){return JSON.stringify(value).replace(/</g,"\\u003c").replace(/>/g,"\\u003e").replace(/&/g,"\\u0026");}
function saveState(){return {filters,series,hiddenSeries,controls:Object.fromEntries(["start","end","query","analysis-text","compare-group","compare-view","compare-metric","pair-min","audit-scope","import-mode"].map(id=>[id,$(id).value])),includeUndated:$("include-undated").checked,candidatesOnly:$("candidates-only").checked};}
function serializeHTML(){const payload={...D,corpora:undefined};return originalHTML.replace(/(<script id="payload" type="application\/json">)[\s\S]*?(<\/script>)/,(m,a,b)=>a+jsonSafe(payload)+b).replace(/(<script id="saved-state" type="application\/json">)[\s\S]*?(<\/script>)/,(m,a,b)=>a+jsonSafe(saveState())+b);}
function download(content,name,type){const blob=new Blob([content],{type}),a=document.createElement("a"),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function csv(rows,fields){const cell=v=>{let text=String(Array.isArray(v)?v.join(" | "):v??"");if(typeof v!=="number"&&/^[=+@\-\t\r]/.test(text))text="'"+text;return '"'+text.replace(/"/g,'""')+'"';};return "\uFEFF"+[fields.map(cell).join(","),...rows.map(r=>fields.map(f=>cell(r[f])).join(","))].join("\r\n");}
function analyticalCSV(){const A=lastAnalytics,output=[],push=(graph,entity,n,d,measure="count",extra="")=>output.push({grafico:graph,categoria:entity,n,denominador:d,percentual:pct(n,d),medida:measure,observacao:extra,texto:$("analysis-text").value,data_inicial:$("start").value,data_final:$("end").value,ambitos:filters.region.join(" | ")});for(const [source,n]of A.sourceCounts)push("Fontes",source,n,A.news.length);for(const [word,n]of A.keywordCounts)push("Palavras-chave",word,n,A.news.length);for(const p of A.profile)for(const v of p.values)push("Perfil temático",p.source+" / "+v.label,v.n,p.n);for(const i of A.intersection)push("Interseção IA/PD",i.label,i.n,A.news.length);for(const p of A.pairs)push("Jaccard",p.a+" + "+p.b,p.n,p.union,"jaccard",String(p.jaccard));for(const c of A.concentration)push("Concentração",c.source,c.n,A.news.length,"share","Acumulada: "+c.cumulative);for(const q of A.quality)for(const key of ["day","month","year","unknown"])push("Qualidade de datas",q.source+" / "+key,q[key],q.n,"quality",$("audit-scope").value);for(const axis of A.axes){push("Eixos / publicações",axis,A.news.filter(r=>r.topics.includes(axis)).length,A.news.length);push("Eixos / catálogo",axis,A.catalog.filter(r=>r.topics.includes(axis)).length,A.catalog.length);}for(const country of A.countries)for(const type of A.types)push("Cobertura",country+" / "+type,A.audit.filter(r=>r.country===country&&r.record_type===type).length,A.audit.length,"coverage",$("audit-scope").value);for(const month of monthLabels(A.news))for(const scope of unique(A.news.map(r=>r.region))){const group=A.news.filter(r=>r.region===scope);push("Evolução mensal",month+" / "+scope,group.filter(r=>r.published_date.startsWith(month)).length,group.length);}return csv(output,["grafico","categoria","n","denominador","percentual","medida","observacao","texto","data_inicial","data_final","ambitos"]);}
function reset(){filters={};series={};hiddenSeries={};$("start").value="";$("end").value=D.metadata.as_of||new Date().toISOString().slice(0,10);$("query").value="";$("include-undated").checked=true;$("candidates-only").checked=false;$("audit-scope").value="selection";buildFilters(false);buildSeries();render();}
$("import-button").onclick=()=>$("import-file").click();$("import-file").onchange=async()=>{try{await importFiles([...$("import-file").files]);}catch(e){message(e.message,true);}finally{$("import-file").value="";}};
$("sync-github").onclick=syncGithub;$("save-html").onclick=()=>{download(serializeHTML(),"Painel_FAPESP_interativo.html","text/html;charset=utf-8");message("HTML atualizado baixado com a base, as cores e os filtros atuais. Abra o arquivo baixado no navegador.");};$("save-data").onclick=()=>download(JSON.stringify({...D,corpora:undefined},null,2),"base_FAPESP.json","application/json");
$("download-selection").onclick=()=>download(csv(selected(),["title","source_id","source","country","region","record_type","published_date","date_precision","url","summary","keywords","topics","match_evidence","collected_at","input_snapshots","manually_selected"]),"selecao_FAPESP.csv","text/csv;charset=utf-8");$("download-analytics").onclick=()=>download(analyticalCSV(),"analises_descritivas_FAPESP.csv","text/csv;charset=utf-8");$("reset").onclick=reset;
$("prev").onclick=()=>{page--;table(selected());};$("next").onclick=()=>{page++;table(selected());};
for(const id of ["start","end","include-undated","candidates-only","pair-min","audit-scope","compare-view","compare-metric"] )$(id).onchange=()=>render();
let queryTimer;$("query").oninput=()=>{clearTimeout(queryTimer);queryTimer=setTimeout(render,180);};$("analysis-text").onchange=()=>{classify(D.documents);render();};$("compare-group").onchange=()=>{buildSeries();render();};$("series-all").onclick=()=>{const f=$("compare-group").value;series[f]=values(f);for(const k of Object.keys(hiddenSeries))if(k.startsWith(f+":"))delete hiddenSeries[k];buildSeries();render();};$("series-none").onclick=()=>{series[$("compare-group").value]=[];buildSeries();render();};
async function exportFigure(el,format){const old=JSON.parse(JSON.stringify(el.layout||{})),height=Math.max(700,old.height||900);try{if(Plotly.relayout)await Plotly.relayout(el,{"font.size":18,"title.font.size":21,"legend.font.size":16,"xaxis.tickfont.size":16,"yaxis.tickfont.size":16,"margin.l":Math.max(75,Math.min(290,old.margin?.l||75)),"margin.t":135});await Plotly.downloadImage(el,{format,width:1000,height,scale:format==="png"?3:1,filename:"FAPESP_"+el.id});}finally{if(Plotly.relayout)await Plotly.relayout(el,old);}}
for(const el of document.querySelectorAll(".chart")){const actions=document.createElement("div");actions.className="chart-actions";for(const format of ["png","svg"]){const b=document.createElement("button");b.textContent="Baixar "+format.toUpperCase();b.onclick=async()=>{b.disabled=true;try{await exportFigure(el,format);}catch(e){message("Falha ao exportar gráfico: "+e.message,true);}finally{b.disabled=false;}};actions.append(b);}el.after(actions);}
if(initialState.controls)for(const [id,value]of Object.entries(initialState.controls))if($(id))$(id).value=value;else {};
if(!initialState.controls){$("start").value="";$("end").value=D.metadata.as_of||new Date().toISOString().slice(0,10);}
filters=initialState.filters||{};series=initialState.series||{};hiddenSeries=initialState.hiddenSeries||{};$("include-undated").checked=initialState.includeUndated===undefined?true:!!initialState.includeUndated;$("candidates-only").checked=!!initialState.candidatesOnly;
D.documents=D.documents.map(r=>normalizeRecord(r,"Base incorporada")).filter(Boolean);classify(D.documents);buildFilters();buildSeries();metadata();message("Base incorporada pronta. Para atualizá-la, importe arquivos dos Colabs ou busque a coleta do GitHub. Depois salve este HTML.");
window.FAPESP={parseCSV,parseDate,normalizeRecord,mergeRecords,importFiles,decodeJSON,selected,color,serializeHTML,saveState,analyticalCSV,render,reset,setFilter:(field,items)=>{filters[field]=items;buildFilters();return render();},getData:()=>D,getFilters:()=>filters};
render();
